# Generated by Django 5.1.3 on 2024-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesstore',
            name='content',
            field=models.JSONField(blank=True, help_text='Введите контент для блока.'),
        ),
    ]
