# Generated by Django 5.1.3 on 2024-12-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesstore',
            name='name',
            field=models.CharField(help_text='Введите название (до 200 символов).', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='informationpagestore',
            name='name',
            field=models.CharField(help_text='Введите название (до 200 символов).', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicestore',
            name='name',
            field=models.CharField(help_text='Введите название (до 200 символов).', max_length=200, unique=True),
        ),
    ]
