# Generated by Django 5.1.3 on 2024-12-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_alter_categoriesstore_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesstore',
            name='content',
            field=models.JSONField(blank=True, help_text='Введите контент для блока.', null=True),
        ),
    ]
